# Generated by Django 6.0.7 on 2026-07-16 04:44

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.mess')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealCountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('lunch_weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('dinner_weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_count_settings', to='accounts.mess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Meal Count Settings',
                'verbose_name_plural': 'Meal Count Settings',
            },
        ),
        migrations.CreateModel(
            name='MealMarkDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('lunch', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('dinner', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_draft', to='accounts.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
            ],
            options={
                'ordering': ['member__name'],
            },
        ),
        migrations.CreateModel(
            name='MemberInputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_enabled', models.BooleanField(default=False)),
                ('morning_start', models.TimeField(default=datetime.time(6, 0))),
                ('morning_end', models.TimeField(default=datetime.time(9, 0))),
                ('lunch_enabled', models.BooleanField(default=False)),
                ('lunch_start', models.TimeField(default=datetime.time(11, 0))),
                ('lunch_end', models.TimeField(default=datetime.time(14, 0))),
                ('dinner_enabled', models.BooleanField(default=False)),
                ('dinner_start', models.TimeField(default=datetime.time(21, 0))),
                ('dinner_end', models.TimeField(default=datetime.time(23, 59, 59))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_input_settings', to='accounts.mess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Member Input Settings',
                'verbose_name_plural': 'Member Input Settings',
            },
        ),
        migrations.CreateModel(
            name='DayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('lunch_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('dinner_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_configs', to='accounts.mess')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('mess', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DayMealLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_locked', models.BooleanField(default=False)),
                ('lunch_locked', models.BooleanField(default=False)),
                ('dinner_locked', models.BooleanField(default=False)),
                ('morning_at', models.DateTimeField(blank=True, null=True)),
                ('lunch_at', models.DateTimeField(blank=True, null=True)),
                ('dinner_at', models.DateTimeField(blank=True, null=True)),
                ('dinner_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
                ('lunch_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_meal_locks', to='accounts.mess')),
                ('morning_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.member')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('mess', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('lunch', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('dinner', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_meals', to='accounts.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_marks', to='accounts.member')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='meals_mealm_date_8d1d71_idx'), models.Index(fields=['member', 'date'], name='meals_mealm_member__f3552a_idx')],
                'unique_together': {('member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('cooking_cost', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_settings', to='accounts.mess')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('mess', 'month', 'year')},
            },
        ),
    ]
