# Generated by Django 6.0.7 on 2026-07-16 04:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('total_exp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dep', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_eff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cook_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_done', to='accounts.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='accounts.mess')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('mess', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_added', to='accounts.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounts.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['member', 'date'], name='finance_dep_member__cb545c_idx'), models.Index(fields=['date'], name='finance_dep_date_aeff00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('rice', 'Rice & Grain'), ('fish', 'Fish & Seafood'), ('meat', 'Meat & Poultry'), ('vegetables', 'Vegetables'), ('oil_spices', 'Oil & Spices'), ('dairy', 'Dairy & Eggs'), ('fuel', 'Gas & Fuel'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_added', to='accounts.member')),
                ('bought_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_bought', to='accounts.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.mess')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='finance_exp_date_677539_idx'), models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClosingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff_meals', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meal_only_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cook_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('verdict', models.CharField(choices=[('paid', 'Paid'), ('received', 'Received'), ('settled', 'Settled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('verdict_note', models.CharField(blank=True, max_length=300)),
                ('verdict_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_records', to='accounts.member')),
                ('verdict_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdicts_given', to='accounts.member')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='finance.mealclosing')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('closing', 'member')},
            },
        ),
    ]
