# Generated by Django 4.2.30 on 2026-07-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('accounts', '0002_mess_approved_at_mess_is_approved_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='meals.announcement'),
        ),
    ]
